import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppProvider } from './_app'
import { ConnectButton } from '@rainbow-me/rainbowkit'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <div
            // style={{
            //   display: 'flex',
            //   justifyContent: 'flex-end',
            //   marginTop: '1rem',
            //   marginRight: '1rem',
            // }}
            className="flex justify-end mt-1 mr-1">
            <ConnectButton />
          </div>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
